#!/usr/bin/env python

import rospy
import smach
import smach_ros
from collections import OrderedDict

from rosplan_tiago_active_human_fall_prevention.msg import HumanApproachDetectAction
from rosplan_tiago_active_human_fall_prevention.msg import HumanApproachDetectActionGoal
from rosplan_tiago_active_human_fall_prevention.msg import HumanApproachDetectActionFeedback
from rosplan_tiago_active_human_fall_prevention.msg import HumanApproachDetectActionResult
from rosplan_knowledge_msgs.srv import *
from rosplan_knowledge_msgs.msg import *
from rosplan_dispatch_msgs.srv import *
from rosplan_dispatch_msgs.msg import *
from std_srvs.srv import *
from rosplan_tiago_common.tiago_kb import TiagoKB


class Initialize(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['init_goal'],
                             output_keys=['init_feedback',
                                          'init_item',
                                          'init_params'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # take goal, check values, split into pose and params, check if params are okay
        # now the server receives only pose
        goal = userdata.init_goal.blind_goal

        userdata.init_item = goal

        rospy.sleep(1)
        return 'ok'


class Dummy(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['dummy_goal',
                                         'dummy_params'],
                             output_keys=['dummy_feedback',
                                          'dummy_info',
                                          'dummy_result'])

    def rosplan_problem_generation(self):
        print "Waiting for service"
        rospy.wait_for_service('rosplan_problem_interface/problem_generation_server')

        print "Preparing the message"
        request_problem = EmptyRequest()

        try:
            print "Calling Problem Generation Service"
            proxy = rospy.ServiceProxy('rosplan_problem_interface/problem_generation_server', Empty)
            update_response = proxy(request_problem)
            print "Response is: ", update_response
        except rospy.ServiceException, e:
            print "Service call failed: %s"%e

    def rosplan_planning(self):
        print "Waiting for service"
        rospy.wait_for_service('rosplan_planner_interface/planning_server')

        print "Preparing the message"
        request_planner = EmptyRequest()

        try:
            print "Calling Planning Service"
            proxy = rospy.ServiceProxy('rosplan_planner_interface/planning_server', Empty)
            update_response = proxy(request_planner)
            print "Response is: ", update_response
        except rospy.ServiceException, e:
            print "Service call failed: %s"%e

    def rosplan_parse_plan(self):
        print "Waiting for service"
        rospy.wait_for_service('rosplan_parsing_interface/parse_plan')

        print "Preparing the message"
        request_parser = EmptyRequest()

        try:
            print "Calling Parse Plan"
            proxy = rospy.ServiceProxy('rosplan_parsing_interface/parse_plan', Empty)
            update_response = proxy(request_parser)
            print "Response is: ", update_response
        except rospy.ServiceException, e:
            print "Service call failed: %s"%e

    def rosplan_dispatch_plan(self):
        print "Waiting for service"
        rospy.wait_for_service('rosplan_plan_dispatcher/dispatch_plan')

        print "Preparing the message"
        request_dispatcher = DispatchServiceRequest()

        try:
            print "Calling Dispatch Plan"
            proxy = rospy.ServiceProxy('rosplan_plan_dispatcher/dispatch_plan', DispatchService)
            update_response = proxy(request_dispatcher)
            print "Response is: ", update_response
        except rospy.ServiceException, e:
            print "Service call failed: %s"%e

    def rosplan_stop_dispatch(self):
        print "Waiting for service"
        rospy.wait_for_service('rosplan_plan_dispatcher/cancel_dispatch')

        print "Preparing the message"
        request_dispatcher = EmptyRequest()

        try:
            print "Calling Cancel Dispatch Plan"
            proxy = rospy.ServiceProxy('rosplan_plan_dispatcher/cancel_dispatch', Empty)
            update_response = proxy(request_dispatcher)
            print "Response is: ", update_response
        except rospy.ServiceException, e:
            print "Service call failed: %s"%e

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # robot movement here - using Tiago move_base
        goal = userdata.dummy_goal
        print goal

        #rospy.sleep(10)

        tiago_kb = TiagoKB()


        # remove scanning area goals
        # dictionary order is IMPORTANT - knowledge values are based on this so i use OrderedDict
        key_value = []
        for i in range(6):
            temp_dict = OrderedDict([("loc_from", "wp{}".format(i)), ("loc_to", "wp{}".format(i+1))])
            key_value.append(temp_dict)

        tiago_kb.add_remove_goals("scanned_area", key_value, should_add=False)

        # remove human_detection_ongoing
        temp_ordered_dict = OrderedDict([("human", "luke")])
        tiago_kb.add_remove_goals("human_detection_ongoing", [temp_ordered_dict], should_add=False)

        # add human_informed goal
        temp_ordered_dict = OrderedDict([("human", "luke")])
        tiago_kb.add_remove_goals("human_informed", [temp_ordered_dict], should_add=True)

        # add robot at initial position
        temp_ordered_dict = OrderedDict([("obj", "rico"), ("loc", "initial")])
        tiago_kb.add_remove_knowledge("at", [temp_ordered_dict], should_add=True)

        # handle "human_coming" fact
        tiago_kb.add_remove_knowledge("human_coming", [], should_add=True)
        tiago_kb.add_remove_knowledge("not_human_coming", [], should_add=True, is_negation=True)
        tiago_kb.add_remove_knowledge("human_coming", [], should_add=False, is_negation=True)
        tiago_kb.add_remove_knowledge("not_human_coming", [], should_add=False)

        self.rosplan_stop_dispatch()

        # wait for actions to be completed
        rospy.sleep(5)

        self.rosplan_problem_generation()

        rospy.sleep(1)
        self.rosplan_planning()

        rospy.sleep(1)
        self.rosplan_parse_plan()

        rospy.sleep(1)
        self.rosplan_dispatch_plan()

        # now exit gently by returning smach ending code
        # rospy.sleep(3)
        # prepare some feedback & result
        action_feedback = HumanApproachDetectActionFeedback()
        action_feedback.feedback.percent_complete = 8
        userdata.dummy_feedback = action_feedback.feedback

        action_result = HumanApproachDetectActionResult()
        action_result.result.is_undocked = 1
        userdata.dummy_result = action_result.result

        return 'preemption'


class Finalize(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['final_info'],
                             output_keys=['final_feedback',
                                          'final_result'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # prepare some feedback & result
        action_feedback = HumanApproachDetectActionFeedback()
        action_feedback.feedback.percent_complete = 8
        userdata.final_feedback = action_feedback.feedback

        action_result = HumanApproachDetectActionResult()
        action_result.result.is_undocked = 1
        userdata.final_result = action_result.result

        # robot approach check may be put here, some distances calculated
        rospy.sleep(2)
        return 'ok'


class HumanApproachDetectServer(smach.StateMachine):
    def __init__(self):
        smach.StateMachine.__init__(self,
                                    outcomes=['PREEMPTED',
                                              'FAILED',
                                              'SM_SUCCEEDED'],
                                    input_keys=['sm_goal'],
                                    output_keys=['sm_feedback',
                                                 'sm_result'])

        # Fill the machine here
        with self:
            smach.StateMachine.add('Initialize',
                                   Initialize(),
                                   transitions={'ok': 'Dummy',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'init_goal': 'sm_goal',
                                              'init_feedback': 'sm_feedback',
                                              'init_item': 'sm_goal',
                                              'init_params': 'sm_params'})

            smach.StateMachine.add('Dummy',
                                   Dummy(),
                                   transitions={'ok': 'Finalize',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'dummy_goal': 'sm_goal',
                                              'dummy_params': 'sm_params',
                                              'dummy_feedback': 'sm_feedback',
                                              'dummy_info': 'sm_info',
                                              'dummy_result': 'sm_result'})

            smach.StateMachine.add('Finalize',
                                   Finalize(),
                                   transitions={'preemption': 'PREEMPTED',
                                                'error': 'FAILED',
                                                'ok': 'SM_SUCCEEDED'},
                                   remapping={'final_info': 'sm_info',
                                              'final_feedback': 'sm_feedback',
                                              'final_result': 'sm_result'})


def main():
    rospy.init_node('human_approach_detect_server')

    # Construct state machine
    sm = HumanApproachDetectServer()

    # # Smach viewer
    sis = smach_ros.IntrospectionServer('human_approach_detect_server', sm, '/SM_HUMAN_APPROACH_DETECT_SERVER')
    sis.start()

    # Construct action server wrapper
    asw = smach_ros.ActionServerWrapper(
        server_name='human_approach_detect',
        action_spec=HumanApproachDetectAction,
        wrapped_container=sm,
        succeeded_outcomes=['SM_SUCCEEDED'],
        aborted_outcomes=['FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='sm_goal',
        feedback_key='sm_feedback',
        result_key='sm_result')

    # Run the server in a background thread
    asw.run_server()
    rospy.spin()
    sis.stop()


if __name__ == '__main__':
    main()
