#!/usr/bin/env python

import rospy
import smach
import smach_ros

from rosplan_tiago_scenarios_msgs.msg import CheckDishwasherAction
from rosplan_tiago_scenarios_msgs.msg import CheckDishwasherActionGoal
from rosplan_tiago_scenarios_msgs.msg import CheckDishwasherActionFeedback
from rosplan_tiago_scenarios_msgs.msg import CheckDishwasherActionResult
from rosplan_tiago_common.tiago_torso_controller import TiagoSpeechController


class Initialize(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        smach.State.__init__(self,
                             outcomes=['remote', 'robot', 'preemption', 'error'],
                             input_keys=['init_goal'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        # take goal, check values, split into pose and params, check if params are okay
        goal = userdata.init_goal.sensor

        if goal == "robot":
            return 'robot'

        return 'remote'


class CallHomeSys(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        rospy.sleep(3)

        return 'ok'


class SetHeight(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        rospy.sleep(3)

        return 'ok'


class SetHeadPose(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        rospy.sleep(3)

        return 'ok'


class InspectDishwasher(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        rospy.sleep(3)

        return 'ok'


class ReleaseHead(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        rospy.sleep(3)

        return 'ok'


class Finalize(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        rospy.sleep(3)

        return 'ok'


class CheckDishwasherServer(smach.StateMachine):
    def __init__(self):
        smach.StateMachine.__init__(self,
                                    outcomes=['PREEMPTED',
                                              'FAILED',
                                              'SM_SUCCEEDED'],
                                    input_keys=['sm_goal'],
                                    output_keys=[])

        # Fill the machine here
        with self:
            smach.StateMachine.add('Initialize',
                                   Initialize(),
                                   transitions={'remote': 'CallHomeSys',
                                                'robot': 'SetHeight',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'init_goal': 'sm_goal'})

            smach.StateMachine.add('CallHomeSys',
                                   CallHomeSys(),
                                   transitions={'ok': 'Finalize',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('SetHeight',
                                   SetHeight(),
                                   transitions={'ok': 'SetHeadPose',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('SetHeadPose',
                                   SetHeadPose(),
                                   transitions={'ok': 'InspectDishwasher',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('InspectDishwasher',
                                   InspectDishwasher(),
                                   transitions={'ok': 'ReleaseHead',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('ReleaseHead',
                                   ReleaseHead(),
                                   transitions={'ok': 'Finalize',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('Finalize',
                                   Finalize(),
                                   transitions={'preemption': 'PREEMPTED',
                                                'error': 'FAILED',
                                                'ok': 'SM_SUCCEEDED'},
                                   remapping={})


def main():
    rospy.init_node('check_dishwasher_server')

    # Construct state machine
    sm = CheckDishwasherServer()

    # # Smach viewer
    sis = smach_ros.IntrospectionServer('check_dishwasher_server', sm, '/SM_CHECK_DISHWASHER_SERVER')
    sis.start()

    # Construct action server wrapper
    asw = smach_ros.ActionServerWrapper(
        server_name='check_dishwasher',
        action_spec=CheckDishwasherAction,
        wrapped_container=sm,
        succeeded_outcomes=['SM_SUCCEEDED'],
        aborted_outcomes=['FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='sm_goal')
        # feedback_key='sm_feedback',
        # result_key='sm_result')

    # Run the server in a background thread
    asw.run_server()
    rospy.spin()
    sis.stop()


if __name__ == '__main__':
    main()
