#!/usr/bin/env python
import rospy
import smach
import smach_ros
import actionlib
import dynamic_reconfigure.client

from geometry_msgs.msg import Pose
from rosplan_tiago_hazard_detection.msg import GoAction, GoActionGoal, GoActionFeedback, GoActionResult
from actionlib_msgs.msg import GoalStatus
from pal_common_msgs.msg import *
from move_base_msgs.msg import *


NAVIGATION_MAX_TIME_S = 30


class Initialize(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        self.dynparam_client = dynamic_reconfigure.client.Client('move_base/PalLocalPlanner')
        self.pal_head_manager_client = actionlib.SimpleActionClient('pal_head_manager/disable', DisableAction)
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['init_goal'],
                             output_keys=['init_feedback',
                                          'init_goal_pose',
                                          'init_params'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        # take goal, check values, split into pose and params, check if params are okay
        # now the server receives only pose
        pose = userdata.init_goal.pose
        userdata.init_goal_pose = pose

        # run pal_head_manager
        # bring back default head movement
        self.pal_head_manager_client.wait_for_server()
        self.pal_head_manager_client.cancel_all_goals()

        # setting planner params so the robot moves normally
        # params = userdata.set_nav_params_params
        params = {
            'max_vel_x': 0.5,
            'acc_lim_x': 0.2
        }
        config = self.dynparam_client.update_configuration(params)

        return 'ok'


class Navigate(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        self.current_pose = Pose()
        self.is_feedback_received = False
        self.move_base_status = GoalStatus.PENDING
        self.is_goal_achieved = False

        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['nav_goal_pose',
                                         'nav_params'],
                             output_keys=['nav_feedback',
                                          'nav_actual_pose',
                                          'nav_result'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        # robot movement here - using Tiago move_base
        pose = userdata.nav_goal_pose

        goal = MoveBaseGoal()
        goal.target_pose.pose = pose
        goal.target_pose.header.frame_id = 'map'
        goal.target_pose.header.stamp = rospy.Time.now()

        client = actionlib.SimpleActionClient('move_base', MoveBaseAction)
        client.wait_for_server()

        # start moving
        client.send_goal(goal, self.move_base_done_cb, self.move_base_active_cb, self.move_base_feedback_cb)

        action_feedback = GoActionFeedback()
        action_result = GoActionResult()
        action_result.result.is_goal_accomplished = False
        userdata.nav_result = action_result.result

        start_time = rospy.Time.now()

        self.is_goal_achieved = False
        while self.is_goal_achieved == False:
            action_feedback.feedback.current_pose = self.current_pose

            userdata.nav_feedback = action_feedback.feedback
            userdata.nav_actual_pose = self.current_pose

            end_time = rospy.Time.now()
            loop_time = end_time - start_time
            loop_time_s = loop_time.secs

            if loop_time_s > NAVIGATION_MAX_TIME_S:
                # break the loop, end with error state
                rospy.logwarn('State: Navigation took too much time, returning error')
                return 'error'

            rospy.sleep(0.1)

        # Here check move_base DONE status
        if self.move_base_status != GoalStatus.SUCCEEDED:
            return 'error'

        return 'ok'

    def move_base_feedback_cb(self, feedback):
        self.current_pose = feedback.base_position.pose
        self.is_feedback_received = True

    def move_base_done_cb(self, status, result):
        self.is_goal_achieved = True
        self.move_base_status = status

    def move_base_active_cb(self):
        return


class Finalize(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['final_actual_pose'],
                             output_keys=['final_result'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        # prepare some feedback & result
        action_result = GoActionResult()
        action_result.result.is_goal_accomplished = True

        userdata.final_result = action_result.result

        return 'ok'


class GoServer(smach.StateMachine):
    def __init__(self):
        smach.StateMachine.__init__(self,
                                    outcomes=['PREEMPTED',
                                              'FAILED',
                                              'APPROACHED'],
                                    input_keys=['sm_goal'],
                                    output_keys=['sm_feedback',
                                                 'sm_result'])

        # Fill the machine here
        with self:
            smach.StateMachine.add('Initialize',
                                   Initialize(),
                                   transitions={'ok': 'Navigate',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'init_goal': 'sm_goal',
                                              'init_feedback': 'sm_feedback',
                                              'init_goal_pose': 'sm_goal_pose',
                                              'init_params': 'sm_params'})

            smach.StateMachine.add('Navigate',
                                   Navigate(),
                                   transitions={'ok': 'Finalize',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'nav_goal_pose': 'sm_goal_pose',
                                              'nav_params': 'sm_params',
                                              'nav_feedback': 'sm_feedback',
                                              'nav_actual_pose': 'sm_actual_pose',
                                              'nav_result': 'sm_result'})

            smach.StateMachine.add('Finalize',
                                   Finalize(),
                                   transitions={'preemption': 'PREEMPTED',
                                                'error': 'FAILED',
                                                'ok': 'APPROACHED'},
                                   remapping={'final_actual_pose': 'sm_actual_pose',
                                              'final_feedback': 'sm_feedback',
                                              'final_result': 'sm_result'})


def main():
    rospy.init_node('go_server')

    # Construct state machine
    sm = GoServer()

    # # Smach viewer
    sis = smach_ros.IntrospectionServer('go_server', sm, '/SM_GO_SERVER')
    sis.start()

    # Construct action server wrapper
    asw = smach_ros.ActionServerWrapper(
        server_name='go',
        action_spec=GoAction,
        wrapped_container=sm,
        succeeded_outcomes=['APPROACHED'],
        aborted_outcomes=['FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='sm_goal',
        feedback_key='sm_feedback',
        result_key='sm_result')

    # Run the server in a background thread
    asw.run_server()
    rospy.spin()
    sis.stop()


if __name__ == '__main__':
    main()
