#!/usr/bin/env python

import rospy
import smach
import smach_ros

from geometry_msgs.msg import Pose

from rosplan_tiago_wandering.msg import GetItemAction
from rosplan_tiago_wandering.msg import GetItemActionGoal
from rosplan_tiago_wandering.msg import GetItemActionFeedback
from rosplan_tiago_wandering.msg import GetItemActionResult

from rosplan_tiago_common.tiago_utils import move_base_set_goal


class Initialize(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['init_goal'],
                             output_keys=['init_feedback',
                                          'init_goal_pose',
                                          'init_params'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # take goal, check values, split into pose and params, check if params are okay
        # now the server receives only pose
        pose = userdata.init_goal.pose

        userdata.init_goal_pose = pose

        rospy.sleep(1)
        return 'ok'


class Navigate(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['nav_goal_pose',
                                         'nav_params'],
                             output_keys=['nav_feedback',
                                          'nav_actual_pose'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # robot movement here - using Tiago move_base
        pose = userdata.nav_goal_pose

        # now movebase
        move_base_set_goal(pose)
        print pose

        rospy.sleep(20)
        return 'ok'


class Finalize(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['final_actual_pose'],
                             output_keys=['final_feedback',
                                          'final_result'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # prepare some feedback & result
        action_feedback = GetItemActionFeedback()
        action_feedback.feedback.time_left = 8
        action_feedback.feedback.is_item_detected = True
        userdata.final_feedback = action_feedback.feedback

        action_result = GetItemActionResult()
        action_result.result.is_item_acquired = True
        userdata.final_result = action_result.result

        # robot approach check may be put here, some distances calculated
        rospy.sleep(2)
        return 'ok'


class GetItemServer(smach.StateMachine):
    def __init__(self):
        smach.StateMachine.__init__(self,
                                    outcomes=['PREEMPTED',
                                              'FAILED',
                                              'APPROACHED'],
                                    input_keys=['sm_goal'],
                                    output_keys=['sm_feedback',
                                                 'sm_result'])

        # Fill the machine here
        with self:
            smach.StateMachine.add('Initialize',
                                   Initialize(),
                                   transitions={'ok': 'Navigate',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'init_goal': 'sm_goal',
                                              'init_feedback': 'sm_feedback',
                                              'init_goal_pose': 'sm_goal_pose',
                                              'init_params': 'sm_params'})

            smach.StateMachine.add('Navigate',
                                   Navigate(),
                                   transitions={'ok': 'Finalize',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'nav_goal_pose': 'sm_goal_pose',
                                              'nav_params': 'sm_params',
                                              'nav_feedback': 'sm_feedback',
                                              'nav_actual_pose': 'sm_actual_pose'})

            smach.StateMachine.add('Finalize',
                                   Finalize(),
                                   transitions={'preemption': 'PREEMPTED',
                                                'error': 'FAILED',
                                                'ok': 'APPROACHED'},
                                   remapping={'final_actual_pose': 'sm_actual_pose',
                                              'final_feedback': 'sm_feedback',
                                              'final_result': 'sm_result'})


def main():
    rospy.init_node('get_item_server')

    # Construct state machine
    sm = GetItemServer()

    # # Smach viewer
    sis = smach_ros.IntrospectionServer('get_item_server', sm, '/SM_GET_ITEM_SERVER')
    sis.start()

    # Construct action server wrapper
    asw = smach_ros.ActionServerWrapper(
        server_name='get_item',
        action_spec=GetItemAction,
        wrapped_container=sm,
        succeeded_outcomes=['APPROACHED'],
        aborted_outcomes=['FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='sm_goal',
        feedback_key='sm_feedback',
        result_key='sm_result')

    # Run the server in a background thread
    asw.run_server()
    rospy.spin()
    sis.stop()


if __name__ == '__main__':
    main()
