#!/usr/bin/env python

import rospy
import smach
import smach_ros

from geometry_msgs.msg import Pose

from rosplan_tiago_wandering.msg import GiveItemAction
from rosplan_tiago_wandering.msg import GiveItemActionGoal
from rosplan_tiago_wandering.msg import GiveItemActionFeedback
from rosplan_tiago_wandering.msg import GiveItemActionResult

from rosplan_tiago_common.tiago_utils import move_base_set_goal


class Initialize(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['init_goal'],
                             output_keys=['init_feedback',
                                          'init_item',
                                          'init_params'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # take goal, check values, split into pose and params, check if params are okay
        # now the server receives only pose
        item = userdata.init_goal.item

        userdata.init_item = item

        rospy.sleep(1)
        return 'ok'


class Dummy(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['dummy_item',
                                         'dummy_params'],
                             output_keys=['dummy_feedback',
                                          'dummy_info'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # robot movement here - using Tiago move_base
        item = userdata.dummy_item

        print item

        rospy.sleep(3)
        return 'ok'


class Finalize(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['final_info'],
                             output_keys=['final_feedback',
                                          'final_result'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # prepare some feedback & result
        action_feedback = GiveItemActionFeedback()
        action_feedback.feedback.time_left = 8
        action_feedback.feedback.is_item_detected = True
        userdata.final_feedback = action_feedback.feedback

        action_result = GiveItemActionResult()
        action_result.result.is_item_given = True
        userdata.final_result = action_result.result

        rospy.sleep(2)
        return 'ok'


class GiveItemServer(smach.StateMachine):
    def __init__(self):
        smach.StateMachine.__init__(self,
                                    outcomes=['PREEMPTED',
                                              'FAILED',
                                              'GAVE_ITEM'],
                                    input_keys=['sm_goal'],
                                    output_keys=['sm_feedback',
                                                 'sm_result'])

        # Fill the machine here
        with self:
            smach.StateMachine.add('Initialize',
                                   Initialize(),
                                   transitions={'ok': 'Dummy',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'init_goal': 'sm_goal',
                                              'init_feedback': 'sm_feedback',
                                              'init_item': 'sm_item',
                                              'init_params': 'sm_params'})

            smach.StateMachine.add('Dummy',
                                   Dummy(),
                                   transitions={'ok': 'Finalize',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'dummy_item': 'sm_item',
                                              'dummy_params': 'sm_params',
                                              'dummy_feedback': 'sm_feedback',
                                              'dummy_info': 'sm_info'})

            smach.StateMachine.add('Finalize',
                                   Finalize(),
                                   transitions={'preemption': 'PREEMPTED',
                                                'error': 'FAILED',
                                                'ok': 'GAVE_ITEM'},
                                   remapping={'final_info': 'sm_info',
                                              'final_feedback': 'sm_feedback',
                                              'final_result': 'sm_result'})


def main():
    rospy.init_node('give_item_server')

    # Construct state machine
    sm = GiveItemServer()

    # # Smach viewer
    sis = smach_ros.IntrospectionServer('give', sm, '/SM_GIVE_ITEM_SERVER')
    sis.start()

    # Construct action server wrapper
    asw = smach_ros.ActionServerWrapper(
        server_name='give_item',
        action_spec=GiveItemAction,
        wrapped_container=sm,
        succeeded_outcomes=['GAVE_ITEM'],
        aborted_outcomes=['FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='sm_goal',
        feedback_key='sm_feedback',
        result_key='sm_result')

    # Run the server in a background thread
    asw.run_server()
    rospy.spin()
    sis.stop()


if __name__ == '__main__':
    main()
