#!/usr/bin/env python

import rospy
import smach
import smach_ros

from geometry_msgs.msg import Pose

from rosplan_tiago_wandering.msg import GreetAction
from rosplan_tiago_wandering.msg import GreetActionGoal
from rosplan_tiago_wandering.msg import GreetActionFeedback
from rosplan_tiago_wandering.msg import GreetActionResult

from rosplan_tiago_common.tiago_utils import move_base_set_goal


class Initialize(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['init_goal'],
                             output_keys=['init_feedback',
                                          'init_greet'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # take goal, check values, split into pose and params, check if params are okay
        # now the server receives only pose
        greet = userdata.init_goal.greet_scenario
        #
        userdata.init_greet = greet

        rospy.sleep(1)
        return 'ok'


class Dummy(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['dummy_greet'],
                             output_keys=['dummy_feedback',
                                          'dummy_greeted_scenario'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        greet = userdata.dummy_greet

        print greet

        rospy.sleep(20)
        return 'ok'


class Finalize(smach.State):
    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['final_greeted_scenario'],
                             output_keys=['final_feedback',
                                          'final_result'])

    def execute(self, userdata):
        rospy.loginfo('Executing state: {}'.format(self.__class__.__name__))

        # prepare some feedback & result
        action_feedback = GreetActionFeedback()
        action_feedback.feedback.percent_complete = 59
        userdata.final_feedback = action_feedback.feedback

        action_result = GreetActionResult()
        action_result.result.is_greeted = True
        userdata.final_result = action_result.result

        rospy.sleep(2)
        return 'ok'


class GreetServer(smach.StateMachine):
    def __init__(self):
        smach.StateMachine.__init__(self,
                                    outcomes=['PREEMPTED',
                                              'FAILED',
                                              'GREETED'],
                                    input_keys=['sm_goal'],
                                    output_keys=['sm_feedback',
                                                 'sm_result'])

        # Fill the machine here
        with self:
            smach.StateMachine.add('Initialize',
                                   Initialize(),
                                   transitions={'ok': 'Dummy',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'init_goal': 'sm_goal',
                                              'init_feedback': 'sm_feedback',
                                              'init_greet': 'sm_greet'})

            smach.StateMachine.add('Dummy',
                                   Dummy(),
                                   transitions={'ok': 'Finalize',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'dummy_greet': 'sm_greet',
                                              'dummy_feedback': 'sm_feedback',
                                              'dummy_greeted_scenario': 'sm_greeted_scenario'})

            smach.StateMachine.add('Finalize',
                                   Finalize(),
                                   transitions={'preemption': 'PREEMPTED',
                                                'error': 'FAILED',
                                                'ok': 'GREETED'},
                                   remapping={'final_greeted_scenario': 'sm_greeted_scenario',
                                              'final_feedback': 'sm_feedback',
                                              'final_result': 'sm_result'})


def main():
    rospy.init_node('greet_server')

    # Construct state machine
    sm = GreetServer()

    # # Smach viewer
    sis = smach_ros.IntrospectionServer('greet_server', sm, '/SM_GREET_SERVER')
    sis.start()

    # Construct action server wrapper
    asw = smach_ros.ActionServerWrapper(
        server_name='greet',
        action_spec=GreetAction,
        wrapped_container=sm,
        succeeded_outcomes=['GREETED'],
        aborted_outcomes=['FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='sm_goal',
        feedback_key='sm_feedback',
        result_key='sm_result')

    # Run the server in a background thread
    asw.run_server()
    rospy.spin()
    sis.stop()


if __name__ == '__main__':
    main()
