#!/usr/bin/env python

import rospy
import smach
import smach_ros

from rosplan_tiago_transportation_attendant.msg import GoWithAttendaceAction
from rosplan_tiago_transportation_attendant.msg import GoWithAttendaceActionGoal
from rosplan_tiago_transportation_attendant.msg import GoWithAttendaceActionFeedback
from rosplan_tiago_transportation_attendant.msg import GoWithAttendaceActionResult
from rosplan_tiago_common.tiago_torso_controller import TiagoSpeechController


class Initialize(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'],
                             input_keys=['init_goal'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        # take goal, check values, split into pose and params, check if params are okay
        goal = userdata.init_goal.human

        return 'ok'


class SetNavParams(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        self.speech_controller = TiagoSpeechController()
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        self.speech_controller.tts('Wait, please!')
        rospy.sleep(3)

        return 'ok'


class SetHeight(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        self.speech_controller = TiagoSpeechController()
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        self.speech_controller.tts('Setting my height!')
        rospy.sleep(3)

        return 'ok'


class TellAboutStart(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        self.speech_controller = TiagoSpeechController()
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        self.speech_controller.tts('You can put item on me now.')
        rospy.sleep(3)

        return 'ok'


class Navigate(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        self.speech_controller = TiagoSpeechController()
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        self.speech_controller.tts('You can put item on me now.')
        rospy.sleep(3)

        return 'ok'


class TellAboutStop(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        self.speech_controller = TiagoSpeechController()
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        self.speech_controller.tts('You can put item on me now.')
        rospy.sleep(3)

        return 'ok'


class SetDefaultParams(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        self.speech_controller = TiagoSpeechController()
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        self.speech_controller.tts('You can put item on me now.')
        rospy.sleep(3)

        return 'ok'


class DefaultHeight(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        self.speech_controller = TiagoSpeechController()
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        self.speech_controller.tts('Bringing back my default height.')
        rospy.sleep(3)

        return 'ok'


class Finalize(smach.State):
    def __init__(self):
        self.node_name = "(" + rospy.get_name() + ")"
        smach.State.__init__(self,
                             outcomes=['ok', 'preemption', 'error'])

    def execute(self, userdata):
        rospy.loginfo('{}: Executing state: {}'.format(self.node_name, self.__class__.__name__))

        # prepare some feedback & result
        # robot approach check may be put here, some distances calculated

        return 'ok'


class GoWithAttendanceServer(smach.StateMachine):
    def __init__(self):
        smach.StateMachine.__init__(self,
                                    outcomes=['PREEMPTED',
                                              'FAILED',
                                              'SM_SUCCEEDED'],
                                    input_keys=['sm_goal'],
                                    output_keys=[])

        # Fill the machine here
        with self:
            smach.StateMachine.add('Initialize',
                                   Initialize(),
                                   transitions={'ok': 'SetNavParams',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={'init_goal': 'sm_goal'})

            smach.StateMachine.add('SetNavParams',
                                   SetNavParams(),
                                   transitions={'ok': 'SetHeight',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('SetHeight',
                                   SetHeight(),
                                   transitions={'ok': 'TellAboutStart',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('TellAboutStart',
                                   TellAboutStart(),
                                   transitions={'ok': 'Navigate',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('Navigate',
                                   Navigate(),
                                   transitions={'ok': 'TellAboutStop',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('TellAboutStop',
                                   TellAboutStop(),
                                   transitions={'ok': 'SetDefault',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('SetDefault',
                                   SetDefault(),
                                   transitions={'ok': 'Finalize',
                                                'preemption': 'PREEMPTED',
                                                'error': 'FAILED'},
                                   remapping={})

            smach.StateMachine.add('Finalize',
                                   Finalize(),
                                   transitions={'preemption': 'PREEMPTED',
                                                'error': 'FAILED',
                                                'ok': 'SM_SUCCEEDED'},
                                   remapping={})


def main():
    rospy.init_node('go_with_attendance_server')

    # Construct state machine
    sm = GoWithAttendanceServer()

    # # Smach viewer
    sis = smach_ros.IntrospectionServer('go_with_attendance_server', sm, '/SM_GO_WITH_ATTENDANCE_SERVER')
    sis.start()

    # Construct action server wrapper
    asw = smach_ros.ActionServerWrapper(
        server_name='go_with_attendance',
        action_spec=GoWithAttendanceAction,
        wrapped_container=sm,
        succeeded_outcomes=['SM_SUCCEEDED'],
        aborted_outcomes=['FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='sm_goal')
        # feedback_key='sm_feedback',
        # result_key='sm_result')

    # Run the server in a background thread
    asw.run_server()
    rospy.spin()
    sis.stop()


if __name__ == '__main__':
    main()
